### PR TITLE
Do not mutate settings object

### PR DESCRIPTION
**Pull request by sapegin**
I have an issue because of mutations in my project: https://github.com/styleguidist/react-styleguidist/issues/348

### CODE REVIEW

**Comment by sapegin** [comment]
@probablyup Could you please review this PR?

**Comment by probablyup** [comment]
Sorry, I've been absolutely swamped at work. I'll make time for this over the weekend. Could you tweak the PR to not use object.assign and instead just do spread applies?

**Comment by sapegin** [comment]
Sure, will do that ;-)

**Comment by probablyup** [comment]
This was merged separately in #97. Thanks for your contribution, and sorry for the delay!

**Pull request closed without merging**
