### PR TITLE
Trim closing hashes from heading

### PR DESCRIPTION
**Pull request by dquenne**
I am trying to switch over to markdown-to-jsx, but I have a lot of existing markdown content that uses trailing hashes in headers, e.g.
```md
### My Header ###
```
Which should be rendered as:

### My Header ###

But instead, using markdown-to-jsx i get:

### My Header ### ###

Which conflicts with the documentation here:
https://github.com/probablyup/markdown-to-jsx/blob/0ce2d88d4419387823cdf5a2c7a2b90e8a475928/fixture.md#L234-L242

It's not straightforward to capture the optional, arbitrary number of hashes at the end of the heading string in the `HEADING_R` regex, so I opted to implement it in the `parse()` method instead. If there's a cleaner way to represent this in `HEADING_R` that I'm not aware of, that's probably better.

### CODE REVIEW

**Comment by dquenne** [comment]
@probablyup can you take a look when convenient?

**Comment by probablyup** [comment]
@dquenne not familiar with this, can you point me to the appropriate markdown syntax documentation?

**Comment by ariabuckles** [comment]
@probablyup Relevant documentation: https://spec.commonmark.org/0.29/#example-41 (I'm not a fan of trying to fully implement commonmark, but it's a decent target for matching when reasonable)

@dquenne your method's reasonable, but I poked around and figured out how to add it to HEADING_R, which I slightly prefer as it avoids the second search + slice, although that comes at the cost of some readability. I've done this in a draft at a600c8474794c5f881be8b11cbe10e2d3465bfab (branch https://github.com/probablyup/markdown-to-jsx/tree/ariabuckles/headings , which I've made sure passes your tests @dquenne )

Does that change seem reasonable to you, or am I missing any edge cases you can see? If it looks good, would it be all right with you if I add that to this PR and then approve this?

**Comment by dquenne** [comment]
@probablyup Sorry I missed your earlier comment!

@ariabuckles Thanks for linking the documentation and providing a much cleaner implementation! By all means add that to this PR and merge 🙂

**Review by ariabuckles — APPROVED** [review]
Thanks @dquenne ! Your tests helped a lot for poking around at the regex :).

@probablyup I'm going to approve/merge this, but leave it for you to handle when it gets released/versioned to npm. If you have any concerns, I'd be happy to help address them before then!

**Pull request merged**
