### PR TITLE
Fix bare URL link with duplicated anchor tag

### PR DESCRIPTION
**Pull request by TheMightyPenguin**
# Description

Fixes an issue where a duplicate anchor tag would get generated when parsing HTML anchor expressions that have a bare URL as the text content.

**NOTE**: This will fix this issue storybookjs/storybook#14176

## Problem

For example, when parsing:

```
<a href="https://example.com">https://example.com</a>
```

The following JSX would be generated:

```
<a href="https://google.com">
  <a href="https://google.com">
    https://google.com
  <a href="https://google.com">
</a>
```

A reproduction can be found in this Codesandbox: https://codesandbox.io/s/markdown-to-jsx--repro-nested-bare-url-ikfo1

Also, it should be noted that this is not valid HTML5 as `a` elements should not have nested interactive content or `a` elements: https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element

This was happening when the inner HTML of a HTML block would try to be parsed, and then this internal part was a URL link, so it would get wrapped in another anchor tag. Related code parts:

* https://github.com/probablyup/markdown-to-jsx/blob/1aeece7546aeafb85a90f12644fd30b9b4f9cf45/index.tsx#L1748
* https://github.com/probablyup/markdown-to-jsx/blob/1aeece7546aeafb85a90f12644fd30b9b4f9cf45/index.tsx#L1310-L1326  

## Proposed Solution

I first added some conditions to the `htmlBlock` rule, to omit processing the content if it was a bare link ([commit](https://github.com/probablyup/markdown-to-jsx/pull/381/commits/f4141d7f03aab622de266b52bb8037cefb51801b)).

But I noticed this would not work with nested URLs inside of anchor tags like:

```
<a href="https://google.com">
  some text
  <span>
    with a link https://google.com
  </span>
</a>
```

This is valid HTML5 as `a` elements can have other non-interactive elements inside.

To handle this, I added a new field to the state, called `inAnchor`, and with this we can return null when matching inside of the `linkBareUrlDetector` rule ([commit](https://github.com/probablyup/markdown-to-jsx/pull/381/commits/b27de52c5c3a5ec1a422f449d4414a342b1b4ab8)).

Both the initial change and the refactor can be seem in the 2 commits in this PR.

Not sure if the solution was the way to go, or if there are more edge cases here, but let me know if anything is missing or could be improved 😄.

### CODE REVIEW

**Comment by TheMightyPenguin** [comment]
@probablyup tagging you in case I need to do so 😄

**Comment by probablyup** [comment]
There's actually a parse method meant specifically for this use case `simpleInlineRegex()`. It's possible it's not being used properly...

**Comment by TheMightyPenguin** [comment]
@probablyup Not 100% sure I got what you meant, but I tried using simple `simpleInlineRegex` inside of `rules.htmlBlock`, with something like:

```
let parseFunc = containsBlockSyntax(trimmed)
  ? parseBlock
  : parseInline

const tagName = capture[1].toLowerCase() as MarkdownToJSX.HTMLTags

if (tagName === 'a') {
  parseFunc = parseSimpleInline
}
``` 

While this does work for cases like:
```
<a href="https://example.com">https://example.com</a>
```

It does not work for nested cases like:
```
<a href="https://google.com">
  some text
  <span>
    with a link https://google.com
  </span>
</a>
```

Because it will still use `parseInline` when parsing the `span` tag. I could also modify the `state.inline` value here, but it would get overridden when `parseInline` is used again. At the moment I don't see other approaches rather than using `state.inAnchor`, but I'm probably missing a lot of context here 😅. @probablyup what are your thoughts? And thanks for the help!

**Review by probablyup — APPROVED** [review]
LGTM thank you!

**Comment by probablyup** [comment]
It's out in 7.1.3 :)

**Pull request merged**
