### PR TITLE
fix: Add "type": "module" to package.json

### LINKED ISSUE #495: cannot use import statement outside a module
When used in Rakkas.

Adding `"type": "module"` to `node_modules/markdown-to-jsx/package.json` helped

### PR DESCRIPTION
**Pull request by greypants**
Fixes #495

### CODE REVIEW

**Review by HPouyanmehr — APPROVED** [review]

**Comment by HPouyanmehr** [comment]
Any updates?
The suggested change is ok and works fine locally. Also, the build error doesn't seem to be relevant to the update by @greypants.

**Comment by ncobourne** [comment]
Currently having to disable some tests due to this issue, would be great if the fix could be added

**Comment by nbarrow-inspire-labs** [comment]
It looks like the test fails not because of the code failing to build, but because of `size-limit` failing: 
```
"size-limit": [
    {
      "path": "dist/index.js",
      "limit": "6 kB"
    }
  ],
```
I see the error `Size Limit can’t find files at dist/index.js`, is this perhaps an issue with the test itself, given that the code is successfully building (given that the actual `yarn build` command return `Done in 17.55s.`)?

**Comment by nbarrow-inspire-labs** [comment]
It looks like changing `type` to `module` affects the build command, such that `index.js` is no longer output, but `index.cjs` (for common) and `index.module.js` (for ES), which in turn affects the `size-limit` config in `package.json` (since the output file `index.js` that the test--`npm run size`--builds on no longer exists. I updated this test in https://github.com/probablyup/markdown-to-jsx/pull/500, and @greypants original suggestion now passes all tests successfully!

**Pull request closed without merging**
