### PR TITLE
feat(compiler): allow replacing of special capital html characters

### PR DESCRIPTION
**Pull request by garywilddev**
Allows HTML character codes starting with a capital letter to be replaced.

https://github.com/probablyup/markdown-to-jsx/issues/447

### CODE REVIEW

**Review by probablyup — APPROVED** [review]
Makes sense to me. Should we add numbers too to support the full range?

**Comment by d3v0ps** [comment]
Hi @probablyup @garywilddev what's the current state of this? can at least the uppercase characters be merged so we can fix those cases? Is there any additional complexity involved on the numeric ones?

**Comment by garywilddev** [comment]
Hi @d3v0ps and @probablyup ,
Sorry I was on long holidays.
I took a look at the code to add support for html numeric codes, but I struggle a bit when using the same approach as for html character codes.
Could we consider merging this PR, as the behaviour for html character codes is satisfactory and I'll open later another Issue and a PR for numeric codes ?

**Comment by probablyup** [comment]
Need to at least get tests passing

**Comment by garywilddev** [comment]
Hi @probablyup,
I merged main into my branch.
Tests are now successful again.

**Review by probablyup — APPROVED** [review]
Awesome, thank you!

**Pull request merged**
