### PR TITLE
disableParsingRawHTML now allows overrides

### PR DESCRIPTION
**Pull request by lowellstewart**
This is added in response to issue #283 and prior pull request #278. It seems like the tests introduced in #278 were ineffective: the tests did not correctly invoke the disableParsingRawHTML option, so the outcome of the tests was not accurate.  This pull request

1) fixes those tests, so they're testing what I think they were meant to test: that overrides should still be honored, even if disableParsingRawHTML === true.  If changed in isolation, these tests would now fail.
2) tweak the parsing so that overrides ARE now still honored, even when disableParsingRawHTML is true.
3) add a couple test cases to make sure that the interaction between disabled raw HTML, and still-enabled overrides, behave as expected -- even when nested.

The change required me to increase the size limit on the script by another few bytes.  Hope it looks okay.  I'm happy to make any changes or refinements you suggest.

### CODE REVIEW

**Comment by probablyup** [comment]
I don't think I'm going to accept this one, if you're opting out of parsing of the HTML you shouldn't be also expecting replacement.

**Comment by lowellstewart** [comment]
I'm sorry to see you've closed this.

As far as I understand, substitutions are the easiest (maybe only?) way to extend the markdown processor, to do things like adding functionality (like a custom tag) that is not part of "markdown proper".  It does not seem unreasonable to me at all, that I may want to offer safe, selective enhancements to the markdown processor to make certain, application-specific features possible (via substitutions), while at the same time NOT wanting my largely non-technical users to be able to enter just any old HTML tags in the markdown (with which they could have a negative impact if they're not careful).

Maybe it just comes down to a differing view of the kinds of problems markdown-to-jsx is aimed at solving?

**Comment by probablyup** [comment]
> Maybe it just comes down to a differing view of the kinds of problems markdown-to-jsx is aimed at solving?

Exactly this. There are a lot of markdown processors out there that do all the bells and whistles, I'm trying to keep this one pretty lean and `disableParsingRawHTML` wasn't something I really wanted to add in the first place to be honest.

**Comment by lampnik** [comment]
I would have liked to see this change been accepted. I'm trying to implement React syntax highlighting for my blog so I, unfortunately, can't opt out of attempting to render React components without removing my <Code> styling override.

**Pull request closed without merging**
