### PR TITLE
add new option namedCodesToUnicode (#236)

### LINKED ISSUE #236: Extend `namedCodesToUnicode` with own/specific html codes
Would it be possible to extend the `namedCodesToUnicode` constant with custom html codes to display them correctly.

Therefore a new `options.namedCodesToUnicode` object could integrated to extend the existing constant list while keeping the list in this repository as small/clean as it is at the moment.

```
options.namedCodesToUnicode = options.namedCodesToUnicode ? {...namedCodesToUnicode, ...options.namedCodesToUnicode} : namedCodesToUnicode;
```

```
…
.replace(HTML_CHAR_CODE_R, (full, inner) => {
              return options.namedCodesToUnicode[inner]
                ? options.namedCodesToUnicode[inner]
                : full;
            }),
…
```

The documentation could also be extended and the new options could work like this:

#### options.namedCodesToUnicode

By default only a couple of named html codes are converted to unicode characters.

* `&` (`&amp;`)
* `'` (`&apos;`)
* `>` (`&gt;`)
* `<` (`&lt;`)
* ` ` (`&nbsp;`)
* `"` (`&quot;`)

Some projects require to extend this map of named codes and unicode characters. To customize this list with additional html codes pass the option `namedCodesToUnicode` as object with the code names needed as in the example below:

```jsx
<Markdown options={{ namedCodesToUnicode: {
    le: '\u2264',
    ge: '\u2265',
} }}>This text is &le; than this text.</Markdown>;

// or

compiler('This text is &le; than this text.', namedCodesToUnicode: {
    le: '\u2264',
    ge: '\u2265',
});

// renders:

<p>This text is ≤ than this text.</p>
```

### PR DESCRIPTION
**Pull request by JeremiasEh**
Fixes #236

### CODE REVIEW

**Comment by JeremiasEh** [comment]
> Nice, thanks!

thanks!
It seems like the npm-package did not successfully has beend updated: https://www.npmjs.com/package/markdown-to-jsx/v/6.10.0 ? because the new options is missing? 🙈

**Comment by probablyup** [comment]
Hmm weird, will take a look later today

**Comment by probablyup** [comment]
@JeremiasEh sorry about that, not sure what happened with the publishing process, super weird. It's fixed in 6.10.1

**Comment by JeremiasEh** [comment]
Thank you very much! I love how fast you are!

> @JeremiasEh sorry about that, not sure what happened with the publishing process, super weird. It's fixed in 6.10.1

**Pull request merged**
