### PR TITLE
breaking refactor: use much lighter parse+compile engine

### PR DESCRIPTION
**Pull request by probablyup**
This package forked the very lightweight [simple-markdown](https://github.com/Khan/simple-markdown) library and now uses its parsing infrastructure. On top of that core functionality, a bunch of improvements have been added:

1. All HTML is now supported natively and dangerouslySetInnerHTML
   is no longer used under any circumstances.

2. Package size is now just ~5kB gzipped, down from ~37kB.

3. Anything rendered via the Markdown component can be overridden now,
   even the wrapper, footnote footer, etc.

I've been working on this release for a while and it took a while to get all the regexes working to my satisfaction. There will probably be bugs, so PRs are welcome to add regression tests as needed and get things tightened up.

Thank you!

### CODE REVIEW

**Comment by probablyup** [comment]
@sapegin would love for you to test this out if you have some spare time

**Comment by sapegin** [comment]
Sounds great! Any API changes? I’ll try it in Styleguidist ;-)

**Comment by probablyup** [comment]
@sapegin no API changes :) should be a drop-in replacement

**Comment by probablyup** [comment]
@sapegin published under `markdown-to-jsx@next` for testing

**Comment by sapegin** [comment]
I already see that you’ve inherited this weird behavior: https://github.com/Khan/simple-markdown/issues/40

**Comment by probablyup** [comment]
@sapegin I actually fixed that: https://github.com/probablyup/markdown-to-jsx/pull/115/files#diff-168726dbe96b3ce427e7fedce31bb0bcR333

A `<div>` might still be added to the result though if there are multiple returns since you can't return an array in React <16.

**Pull request merged**
