### PR TITLE
Add an option to disable parsing of bare urls

### PR DESCRIPTION
**Pull request by pauledwards241**
We've been struggling with the automatic bare url parsing from `markdown-to-jsx` and would love a way to disable this functionality.

For us, it causes an issue when we've written HTML links into our markdown because we'd like that link to open in a new tab. 

If the anchor content is a valid URL, the compiler will parse the anchor content and then also the anchor element generating two links in the output, the first one being invisible to the user.

For example:

**Input**
```
<a href="https://google.co.uk" rel="noopener noreferrer" target="_blank">https://google.co.uk</a>
```

**Output**
```
<a href="https://google.co.uk" rel="noopener noreferrer" target="_blank"></a>
<a href="https://google.co.uk">https://google.co.uk</a>
```

### CODE REVIEW

**Comment by probablyup** [comment]
I think this is a bug with the HTML parser not having priority over the link recognizer. Probably just need to adjust the priorities in the rules...

**Comment by pauledwards241** [comment]
Interesting, I just tried setting the `order` property of `linkBareUrlDetector` to `Priority.MIN` as an experiment, but it didn't seem to make a difference. I assume it still detects the URL regardless of what stage in the process it is?

Could an alternative be to update the `LINK_AUTOLINK_BARE_URL_R` regex to not detect links surrounded by `>` and `<`? That felt a little hacky to me though.

Sorry if I've misunderstood what you were asking.

**Comment by probablyup** [comment]
@pauledwards241 seems fine to me, can you add documentation to the README?

**Comment by pauledwards241** [comment]
@probablyup I started updating the readme, but this actually seems more of a bug rather than an additional feature like you originally said. I can't really think of a reason to disable this feature if it works correctly.

I plan to do some digging to see if I can find the cause. I'm going to leave this open for now, but will update you hopefully soon.

**Comment by pauledwards241** [comment]
@probablyup I did some digging into the code around this issue and decided that the simplest option might be to add the `disableParsingBareUrls` option.

I added a solution around disabling this rule for `<a>` elements, which worked fine, but then if someone was to have a custom link element e.g. `<Link href="https://github.com">https://github.com</Link>`, this problem would occur again. It feels like we would then need to allow rule disabling on overrides, which seems a bit overkill.

Anyway, I've updated the readme. If you'd prefer I kept this in a fork if you're not sure it would be useful to others, that's also fine. Please let me know either way 🙂  Thanks.

**Comment by TheMightyPenguin** [comment]
@pauledwards241 @probablyup I added a fix for this in this PR https://github.com/probablyup/markdown-to-jsx/pull/381

The library should not process bare links if they're inside an anchor, as that generates invalid HTML5 according to the [spec](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element).

**Comment by TheMightyPenguin** [comment]
@pauledwards241 is this still needed now that #381 has been merged? I fixed the double nested anchor tags in that PR, so not sure if that will be enough for your use case.

(Also, just realized the PR came from Media Molecule, I love games from Media Molecule, Little Big Planet is what got me into software engineering, so I wanted to give a shout out to the team there! 🙌)

**Comment by pauledwards241** [comment]
Hi @TheMightyPenguin thanks for your comment, I'm happy to close this and take a look at your changes. Would be great to not have to maintain a separate fork.

Also, thanks for the Media Molecule love, I'm glad Little Big Planet helped to inspire you 😀

**Pull request closed without merging**
